CREATE TABLE IF NOT EXISTS "http_pushers" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "number" TEXT NOT NULL,
  "url" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "header" TEXT NOT NULL,
  "field" TEXT NOT NULL,
  "to_string" BOOLEAN NOT NULL
);
